{% set name = "localstack-client" %}
{% set version = "0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d0228be24dd432aff030275b9ea3f3c7c52d70b7cefd12ff4100c26e2edcf6d4

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - python

test:
  imports:
    - localstack_client

about:
  home: "https://github.com/localstack/localstack-python-client"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE"
  summary: "A lightweight Python client for LocalStack."
  doc_url: "https://pypi.org/project/localstack-client/"
  dev_url: "https://github.com/localstack/localstack-python-client"

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
