{% set name = "localstack-client" %}
{% set version = "1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcbcde7ce885bd951835cb8bd48ad6fd1423c6ab271a7f74ee200fa5ec77052a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - boto3
    - python

test:
  imports:
    - localstack_client

about:
  home: https://github.com/localstack/localstack-python-client
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A lightweight Python client for LocalStack.
  doc_url: https://pypi.org/project/localstack-client/
  dev_url: https://github.com/localstack/localstack-python-client

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
