travis:
  secure:
    BINSTAR_TOKEN: PHJvlI2NWt1+aYF3TzUTnSp7ENgTC7p3q11VN3Xw7H91og3qNuOa4OOcksEelsCI5JZNIRdKn/rzsRb6ND4O5Nie1SRNProbaCpFDrVOXTVwsUoXpP8OiSzoLkksPsVpfE8j76pmQdXuQYk2Ts7yi2ztQ1QJXY16aYUis8F5TvYsxqKuY4mZEwInLwbhvWEqRovs959+3AgV2NHj3qm3oYHJMfTXUAB+9NRPs6r0W4jzA0R9/1XvrG2kCe8f1Z1B9aCQ5h6+VOWbBEi8rfoOKwavZGGFgefTYv3RE6aEJo68JvAXrNRRu7WYlQluQ+FwafB9no6bvA9JsPPboVm9LeEfHxiJHlMByqkkEDn3MWVKi/NYp05tE6m8G5Gt0dRh7/zTaovJfWJdsC0a2eaxaiGE3xaWRSe3Jp/mgYbUFuaYJqHb9jjFwEvHA6HDVjNK3JgAtakeDxnOQnaY981tIxZncW8liqrxA/vaP9Eq/8tYnEIvCklxUDAamKR6VCEFHKMEU3wODK+3IL8+xJ7TCk6Q4YWI3u5pGXcUmSpU8q52pkxu7S0ks9t7tRLy+OTdmEq42igHaERSvnAo+l+WGGxb0pRxKJytrMWiLNONVzXc55QnyaPvsm2AiZe5eNtYEiobzgQzHiSU6maA9BWqc2tl5WXJ7UdEUUspO/XZBwE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
